name: Documentation

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install mkdocs mkdocs-material

      # Build the documentation
      - name: Build MkDocs site
        run: |
          mkdocs build

      # Upload built site as artifact
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: site/

  deploy:
    name: Deploy Documentation
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: site/
